# Generated by Django 5.2 on 2026-04-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Displayed on the verification page, e.g. 'Caleb Book Sale'", max_length=200)),
                ('slug', models.SlugField(help_text="URL identifier, e.g. 'caleb-book-sale' → ?c=caleb-book-sale", unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional subtitle shown under the campaign name')),
                ('allowed_domains', models.TextField(help_text='Comma-separated school email domains allowed for this campaign, e.g. caleb.edu.ng,stu.cu.edu.ng')),
                ('selar_url', models.URLField(help_text='Selar product page students are redirected to after getting their code')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive campaigns return 404 to the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='assignedcoupon',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verification.coupon'),
        ),
        migrations.AlterField(
            model_name='assignedcoupon',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coupons', to='verification.studentverification'),
        ),
        migrations.AddField(
            model_name='assignedcoupon',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_coupons', to='verification.campaign'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Which campaign this code belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coupons', to='verification.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='assignedcoupon',
            unique_together={('student', 'campaign')},
        ),
    ]
